[package]
name = "koi-lexer"
version = "0.3.0-alpha.3"
edition = "2021"
description = "Lex Koi source code."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
